apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: testapp-svc-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 5000
      name: http
      protocol: HTTP
    hosts:
    - "*"
  
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testapp-svc