apiVersion: v1
kind: Service
metadata:
  name: testapp-svc-2
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: testapp-svc-2
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: 'true'
  labels:
    app: testapp-svc-2
  name: testapp-svc-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-svc-2
  template:
    metadata:
      labels:
        app: testapp-svc-2
    spec:
      containers:
<<<<<<< HEAD
      - image: ratnadeepb/testapp:jaeger
        imagePullPolicy: Always
=======
      - image: ratnadeepb/testapp:bad-leaves
>>>>>>> da412231548aaa7697b26f752019b066fb585517
        name: testapp-svc-2
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 1500m
            memory: 100Mi
          requests:
            cpu: 1000m
            memory: 50Mi
