apiVersion: v1
kind: Service
metadata:
  name: testapp-svc-2
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 5000
  selector:
    app: testapp-svc-2
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp-svc-2
  name: testapp-svc-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-svc-2
  template:
    metadata:
      labels:
        app: testapp-svc-2
    spec:
      containers:
      - image: ratnadeepb/testapp
        name: testapp-svc-2
        ports:
        - containerPort: 5000
